### ISSUE TITLE
Sling Free TV

### ISSUE THREAD

**Issue by Protektor-Desura** [fHDHR/fHDHR#118]
Sling Free TV - Sling offers a number of channels for free to the public.
https://watch.sling.com/

**Comment by tv21** [comment]
If it makes any difference, Sling is the one I'd vote for simply because they have an actual guide that goes out for a week.  Pluto has a better selection of channels if you just want to channel surf, but if you actually want to plan your viewing for more than the three or four hours their guide covers you are out of luck, and that makes Pluto pretty useless for anyone other than casual channel surfers.  Sling has far fewer live channels but as I said above their guide has a week's worth of listings, which makes their site actually useful if you want to plan ahead.
