### ISSUE TITLE
Did you kill Ceton support?

### ISSUE THREAD

**Issue by JSylvia007** [fHDHR/fHDHR#79]
What happened?  I see now that the Ceton "branch" is gone when I tried to do a git pull...  So I created another directory and checked out the main repo, and using my previous config, none of the ceton options show up...

:-(

**Comment by deathbybandaid** [comment]
Please glance at the new docs.

We've moved to a plugin system.

**Comment by deathbybandaid** [comment]
https://github.com/fHDHR/fHDHR_plugin_origin_ceton

**Comment by deathbybandaid** [comment]
If you want hdhr capability, make sure you grab that plugin as well.

You will also want the ffmpeg plugin for ceton

**Comment by JSylvia007** [comment]
Appreciate the pointer in the right direction.  I think I'm making progress yet again.  Bummer that I have to set it all up from scratch again, but hopefully this leads to a more stable setup overall!

Thanks for all the work you guys are doing!

**Comment by DanAustinGH** [comment]
The restructuring simplifies makes life easier fo DbB, since he does not have to make the same change almost two dozen times.  The process has allowed for several cool new features, so that would have required a fresh database, and allows you to pick the exact modules you want.  If you don't need a guide, don't load an EPG plugin, etc.  It has also caused me to learn a bit more about the framework and fix a few issue that were unique to the Ceton.

**Comment by JSylvia007** [comment]
> The restructuring simplifies makes life easier fo DbB, since he does not have to make the same change almost two dozen times. The process has allowed for several cool new features, so that would have required a fresh database, and allows you to pick the exact modules you want. If you don't need a guide, don't load an EPG plugin, etc. It has also caused me to learn a bit more about the framework and fix a few issue that were unique to the Ceton.

Awesome!!  Still in the process of having the channel database re-created.
